version: '3.8'
services:
  postgres:
    image: postgres:17-alpine
    container_name: dialogue-postgres-container
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dialogue
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: dialogue-redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data: