services:
  db:
    image: neondatabase/neon_local:latest
    container_name: dialogue-db
    env_file:
      - .env
    ports:
      - '5432:5432'
    environment:
      NEON_API_KEY: ${NEON_API_KEY}
      NEON_PROJECT_ID: ${NEON_PROJECT_ID}
      DRIVER: serverless
  cache:
    image: redis:8-alpine
    container_name: dialogue-cache
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "6379:6379"